[wokwi]
version = 1
firmware = "build/Wokwi.ino.merged.bin"
elf = "build/Wokwi.ino.elf"

[[package]]
name = "Adafruit SSD1306"

[[package]]
name = "Adafruit GFX Library"

[[package]]
name = "PubSubClient"

[[package]]
name = "ArduinoJson"

[[package]]
name = "WiFiManager"
